### ISSUE TITLE
Building and dtc, dtb

### ISSUE THREAD

**Issue by gexpult** [franzflasch/linux_for_riscv_em#2]
Hi!

I compiled the firmware and emulator. What is `dtc`? I don't know how to build the `dtb` file.

**Comment by franzflasch** [comment]
Hi!

I've only built this with my own toolchain. You can grab a prebuilt one here, if you want: https://github.com/franzflasch/gcc-build-tools

Nevertheless it should also work with your toolchain. 

How much RAM do you have on your system? On my system I have 8G available.

**Comment by franzflasch** [comment]
OK my answer is for the question before the edit. Did you manage to build linux now?

dtc stands for device-tree compiler. It compiles the .dts (device tree source) into a dtb (device tree binary). It is needed to run linux. It basically necessary for linux to know which devices (cpu, memory, etc) the system it is running on has.

In ubuntu you can install it with:
`sudo apt install device-tree-compiler`

**Comment by franzflasch** [comment]
I've added a script (inside the dts directory of riscv_em) to build the device-tree binary:
`build_dtb.sh`
