### ISSUE TITLE
Links to toolchain collections are broken

### ISSUE THREAD

**Issue by hgesser** [franzflasch/linux_for_riscv_em#4]
Hi, 
I've tried the two links for the RISCV32 and RISCV64 toolchain zip archives, and they are both broken. The error message is:
```
Error 404 – Not Found
GitHub produced an error for the download of artifact #359688336.
Usually this means that the artifact has expired (>90 days).
```
Greetings, Hans-Georg

**Comment by franzflasch** [comment]
Hi! Yes I know. They always expire 90 days after the last push of https://github.com/franzflasch/gcc-build-tools

I think this needs some updates anyway so I'll fix it today.

**Comment by franzflasch** [comment]
Should be fixed now

**Comment by hgesser** [comment]
Yes, works for me now, thanks!
