### ISSUE TITLE
fw_payload.bin does not display any output in riscv_em

### ISSUE THREAD

**Issue by mikechambers84** [franzflasch/linux_for_riscv_em#7]
I got this to build, but when I run the payload bin in riscv_em, it just sits there with no output no matter how long I wait. I'm not sure what the issue could be. Do you have a known working fw_payload.bin for RV32 MMU that I could try?

![image](https://github.com/franzflasch/linux_for_riscv_em/assets/904313/1c86174b-b440-4472-b935-06db67a40399)

**Comment by franzflasch** [comment]
You need to compile the .dts file to .dtb (device tree blob) using the .dts directly does not work.

Its described in the riscv_em repository how to do that.

**Comment by mikechambers84** [comment]
Thank you for replying! Yes, I realized it minutes after I posted the issue so I closed it. It's working!

I was trying to test it out as-is first, and am planning to add networking support to it. I would also like to get it running on embedded systems and maybe even vintage PC hardware just for fun.

Great work on this, it's well-written!

**Comment by franzflasch** [comment]
Thanks :)
